// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJSqI-GSxpQoSjk6i3GxDX09u2tZc2D4',
    appId: '1:393406418127:web:705e366fcb87a9f1543bba',
    messagingSenderId: '393406418127',
    projectId: 'campus-move00',
    authDomain: 'campus-move00.firebaseapp.com',
    storageBucket: 'campus-move00.firebasestorage.app',
    measurementId: 'G-12Q2WYPMG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN4E2-TbxmHGbydD7d27i-k58qPVUazVc',
    appId: '1:393406418127:android:98d31cd95c184f8f543bba',
    messagingSenderId: '393406418127',
    projectId: 'campus-move00',
    storageBucket: 'campus-move00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZUX-o2H_DVAqf_yWeaLzFyY1kghssDjI',
    appId: '1:393406418127:ios:8c57ce9d9035b638543bba',
    messagingSenderId: '393406418127',
    projectId: 'campus-move00',
    storageBucket: 'campus-move00.firebasestorage.app',
    iosBundleId: 'com.example.campusMove00',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZUX-o2H_DVAqf_yWeaLzFyY1kghssDjI',
    appId: '1:393406418127:ios:8c57ce9d9035b638543bba',
    messagingSenderId: '393406418127',
    projectId: 'campus-move00',
    storageBucket: 'campus-move00.firebasestorage.app',
    iosBundleId: 'com.example.campusMove00',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvJSqI-GSxpQoSjk6i3GxDX09u2tZc2D4',
    appId: '1:393406418127:web:1dbb6061f018b9e0543bba',
    messagingSenderId: '393406418127',
    projectId: 'campus-move00',
    authDomain: 'campus-move00.firebaseapp.com',
    databaseURL: 'https://campus-move00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-move00.firebasestorage.app',
    measurementId: 'G-9V0NEM0BDM',
  );
}
